server:
  port: 8082
  servlet:
    context-path: /notification
brevo:
  key: "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"

spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/notification-service?authSource=admin
