server:
  port: 8082
  servlet:
    context-path: /notification
notification:
  brevoKey: "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"
  brevoApiUrl: "https://api.brevo.com/"

spring:
  application:
    name: notification-service
  data:
    mongodb:
#      uri: mongodb://root:root@localhost:27017/notification-service?authSource=admin
      uri: mongodb://root:root@localhost:27017/notification-service?authSource=admin
  kafka:
      bootstrap-servers: localhost:9094
#      bootstrap-servers: kafka:9092
      consumer:
        group-id: notification-group
        auto-offset-reset: earliest
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
#        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
#        key-serializer: org.apache.kafka.common.serialization.StringSerializer
#        value-serializer: org.springframework.kafka.support.serializer.StringSerializer

#        key-serializer: org.apache.kafka.common.serialization.JsonDeserializer
#        value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted.packages: "*"
#      producer:
#        key-serializer: org.apache.kafka.common.serialization.StringSerializer
#        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#        retries: 3
#        acks: all
