## spring.application.name=supplier-service
server:
  port: 8083
  servlet:
    context-path: /supplier

spring:
  application:
    name: supplier-service

  datasource:
    url: jdbc:postgresql://localhost:5433/supplier_service
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  logging:
    level:
      org.springframework: INFO
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
